// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcUgxiLOzbGGwwb2aNJOfiDqe0K-mivM',
    appId: '1:641232184873:web:e68ef8c29915f947039e38',
    messagingSenderId: '641232184873',
    projectId: 'examapp-f6430',
    authDomain: 'examapp-f6430.firebaseapp.com',
    storageBucket: 'examapp-f6430.firebasestorage.app',
    measurementId: 'G-L0Q3XD06CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1DDacb9Lxag8CyeUfeILzDmMX0XIvC8',
    appId: '1:641232184873:android:e4979caf00caf542039e38',
    messagingSenderId: '641232184873',
    projectId: 'examapp-f6430',
    storageBucket: 'examapp-f6430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4xlw0LaH04pQ2njSUfTWfH0Xi-TM3unM',
    appId: '1:641232184873:ios:d634ef8ec3260863039e38',
    messagingSenderId: '641232184873',
    projectId: 'examapp-f6430',
    storageBucket: 'examapp-f6430.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4xlw0LaH04pQ2njSUfTWfH0Xi-TM3unM',
    appId: '1:641232184873:ios:d634ef8ec3260863039e38',
    messagingSenderId: '641232184873',
    projectId: 'examapp-f6430',
    storageBucket: 'examapp-f6430.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGcUgxiLOzbGGwwb2aNJOfiDqe0K-mivM',
    appId: '1:641232184873:web:f9a63623a84ea93a039e38',
    messagingSenderId: '641232184873',
    projectId: 'examapp-f6430',
    authDomain: 'examapp-f6430.firebaseapp.com',
    storageBucket: 'examapp-f6430.firebasestorage.app',
    measurementId: 'G-YWNSMMQ5GF',
  );
}
